### ISSUE TITLE
Mods with custom audio appear to be broken

### ISSUE THREAD

**Issue by Tarryem** [LAGonauta/metahook#1]
I've attempted to use this with some mods such as this: (https://www.moddb.com/mods/half-life-2-classic) and this: (https://www.moddb.com/mods/yet-another-ps2-half-life-pc-port) but no audio plays at all, it's completely silent in the latest versions.

**Comment by LAGonauta** [comment]
Which version are you using? Please write "al_version" in the console.
You must extract sound data from pak files if they are used (seems to be used on PS2 HL), the plugin cannot read from them yet.

**Comment by LAGonauta** [comment]
If those mods use .pak files they will work on the next release.
