### ISSUE TITLE
Error with hardware sound acceleration using

### ISSUE THREAD

**Issue by El-0scuro** [LAGonauta/metahook#11]
In README was stated, that for hardware acceleration it's need to remove OpenAL32.dll
After that, i had this error - what's wrong i've done?
Creative X-Fi Titanium HD PCI-E soundcard, if's it's important.
![error](https://user-images.githubusercontent.com/54748439/64066868-ea683700-cc27-11e9-808b-15982ce787b8.PNG)

**Comment by LAGonauta** [comment]
Are you on Game Mode? That error should have been fixed on the latest release, what version are you using?

**Comment by El-0scuro** [comment]
Hmmm.... I could swear that I've checked that feature with Game Mode, but it works. Thanks. Closing issue.
