### ISSUE TITLE
hl.exe doesn't start

### ISSUE THREAD

**Issue by HarGabt** [LAGonauta/metahook#5]
The game just refuses to start, it crashes at splashscreen, and creates a .mdmp file after.
i tried this with Half-Life, 

Counter-Strike 1.6 just crashes with "Protector v4: couldn't find PClient pointer."

[Steam_2019_06_02__17_15_51_940.zip](https://github.com/LAGonauta/metahook/files/3245004/Steam_2019_06_02__17_15_51_940.zip)

**Comment by LAGonauta** [comment]
I will take a look and get back to you. Are you using the newest Steam release? Any betas?

**Comment by LAGonauta** [comment]
@HarGabt 
Just tested with newest CS 1.6 from Steam and it is working. Are you still having this problem?

**Comment by LAGonauta** [comment]
@HarGabt Are you still seeing crashes?

**Comment by LAGonauta** [comment]
Closed due to inactivity.
