### ISSUE TITLE
Problems with hl from the launcher

### ISSUE THREAD

**Issue by M00nBr1ght** [LAGonauta/metahook#8]
a lot of the aspect ratios can just go off screen, the only way I have found to fix this is to plug and unplug my second monitor, and not this happens without a second monitor so I'm not sure if there is another way to fix this otherwise.

The other big problem I have is the mouse input, it puts the mouse too close to the edge of the screen so it shows up when it hits it, and sometimes it just won't lock the mouse at all so I will see it and tab out in my second monitor.

**Comment by LAGonauta** [comment]
Recently I found out that you must disable Windows scaling for metahook.exe in the compatibility tab, maybe this is what is happening there?

**Comment by LAGonauta** [comment]
@M00nBr1ght Are you still having problems?

**Comment by LAGonauta** [comment]
Closed due to inactivity.
