### ISSUE TITLE
Error when trying to run through steam

### ISSUE THREAD

**Issue by M00nBr1ght** [LAGonauta/metahook#9]
when trying to run through steam I get the fatal error saying 

> Failed to initialize authentication interface. Exiting

**Comment by arnalll** [comment]
hmmm.. are you sure steam is running?

**Comment by LAGonauta** [comment]
@M00nBr1ght Are you still having problems?

**Comment by LAGonauta** [comment]
Closed due to inactivity.

**Comment by M00nBr1ght** [comment]
Oh shit, sorry I never got back to this, it's been months and I have given up on the project of trying to get it to work, if you have any questions please feel free to still use this thread

**Comment by meetajhu** [comment]
Running the game in administrator mode fixed this.
